#!/bin/bash

# Manual PostgreSQL Migration Steps
# Run these commands one by one in your terminal

echo "==================================================================="
echo "PostgreSQL Migration - Manual Steps"
echo "==================================================================="
echo ""
echo "Copy and paste these commands in your terminal:"
echo ""
echo "# 1. Start PostgreSQL (requires sudo)"
echo "cd /home/yassen/Development/Projects\\ /Sahary-Cloud/backend"
echo "sudo docker-compose -f docker-compose.dev.yml up -d postgres redis"
echo ""
echo "# 2. Wait for PostgreSQL to start"
echo "sleep 10"
echo ""
echo "# 3. Check if PostgreSQL is running"
echo "sudo docker ps | grep postgres"
echo ""
echo "# 4. Generate Prisma Client"
echo "npx prisma generate"
echo ""
echo "# 5. Run Migration"
echo "npx prisma migrate dev --name init_postgresql"
echo ""
echo "# 6. Verify tables were created"
echo "sudo docker exec sahary-postgres psql -U sahary_user -d sahary_cloud -c '\\dt'"
echo ""
echo "# 7. Start backend server"
echo "npm run dev"
echo ""
echo "==================================================================="
echo "After running these commands, your database will be migrated!"
echo "==================================================================="
